parameters:
    twig.loader.bundle.class: Brother\CommonBundle\Twig\BundleLoader
    doctrine.data_collector.class: Brother\CommonBundle\DataCollector\DoctrineDataCollector
    doctrine.dbal.logger.profiling.class: Brother\CommonBundle\Logger\DebugStack

services:

    logger:
        class: Psr\Log\NullLogger

    brother_common.sphinx_logger:
        public: true
        class: Brother\CommonBundle\Logger\SphinxLogger
        tags: [ { name: "monolog.logger", channel: "brother_common_sphinx" } ]
        arguments: [ '@logger' ]

    brother_common.sphinx_collector:
        class: Brother\CommonBundle\DataCollector\SphinxDataCollector
        public: false
        tags:
            -   name: data_collector
                template: BrotherCommonBundle:Collector:sphinx.html.twig
                id: sphinx
        arguments: [ '@brother_common.sphinx_logger' ]

    brother_cache:
        public: true
        class: Brother\CommonBundle\Cache\BrotherCacheProvider
        arguments: [ '@snc_redis.cache' ]

    brother_cache_fast:
        class: Brother\CommonBundle\Cache\BrotherCacheProvider
        arguments: [ '@snc_redis.fast' ]

    twig.loader.bundle:
        class: '%twig.loader.bundle.class%'
        arguments:
            - '@twig.loader.native_filesystem'
        tags:
            - { name: twig.loader }
    #    twig.loader.string:
    #        class: %twig.loader.string.class%
    #        tags:
    #            - { name: twig.loader }
    #
    #    vendor.bundle.twig_database_loader:
    #        class: Vendor\Bundle\Twig\TwigDatabaseLoader
    #        arguments: [ @doctrine.orm.entity_manager ]
    #        tags:
    #            - { name: twig.loader }
    knp_paginator.subscriber.mongo:
        class: Brother\CommonBundle\Model\MongoDB\QuerySubscriber
        tags: [ { name: "knp_paginator.subscriber" } ]

    knp_paginator.subscriber.sphinx:
        class: Brother\CommonBundle\Model\Sphinx\QuerySubscriber
        tags: [ { name: "knp_paginator.subscriber" } ]
