parameters:
services:

    brother_common.sphinx_logger:
        class: Brother\CommonBundle\Logger\SphinxLogger
        tags: [{name: "monolog.logger", channel: "brother_common_sphinx"}]
        arguments: [ @logger ]

    brother_common.sphinx_collector:
        class: Brother\CommonBundle\DataCollector\SphinxDataCollector
        public: false
        tags:
            -
                name: data_collector
                template: BrotherCommonBundle:Collector:sphinx.html.twig
                id: sphinx
        arguments: [ @brother_common.sphinx_logger ]

    brother_cache:
        class: Brother\CommonBundle\Cache\BrotherCacheProvider
        arguments: [ @snc_redis.cache ]

    brother_cache_fast:
        class: Brother\CommonBundle\Cache\BrotherCacheProvider
        arguments: [ @snc_redis.fast ]
