<?php

/*
 * This file is part of the Sonata package.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Brother\CommonBundle\Admin\Entity;

use Brother\CommonBundle\AppDebug;
use Brother\CommonBundle\Route\AppRouteAction;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\MediaBundle\Admin\ORM\MediaAdmin as Admin;

class MediaAdmin extends Admin
{
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        parent::configureDatagridFilters($datagridMapper); // TODO: Change the autogenerated stub
        $datagridMapper->add('user');
    }


    public function getFilterParameters()
    {
        $parameters = parent::getFilterParameters(); // TODO: Change the autogenerated stub
        if (!empty($parameters['context']['value']) && $parameters['context']['value'] == 'profile') {
            $parameters['user']['value'] = AppRouteAction::getUserId();
        }
        return $parameters;
    }

}
