<?php

/*
 * This file is part of the Sonata package.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Brother\CommonBundle\Admin\Entity;

use Sonata\AdminBundle\Form\FormMapper;
use Sonata\UserBundle\Admin\Model\UserAdmin as BaseUserAdmin;

class UserAdmin extends BaseUserAdmin
{
    protected function configureFormFields(FormMapper $formMapper)
    {

        parent::configureFormFields($formMapper); // TODO: Change the autogenerated stub

        $now = new \DateTime();
        $formMapper->tab('User')->with('Profile')->add('dateOfBirth', 'sonata_type_date_picker', array(
            'dp_language'=>'ru','format'=>'dd.MM.yyyy',
            'years' => range(1900, $now->format('Y')),
            'dp_min_date' => '1-1-1900',
//                        'dp_max_date' => $now->format('c'),
            'required' => false
        ));
    }


}
